[package]
name = 'cashier-server'
description = 'Cashier Ledger-cli server component'
version = '0.4.0'
edition = '2021'
authors = ['Alen Šiljak']
repository = 'https://github.com/alensiljak/cashier-server-rust'
categories = ['command-line-utilities', 'web-programming::http-server']
license = 'GPL-3.0-or-later'
readme = "README.md"

[dependencies]
axum = { version = "0.6.1", features = ['headers'] }
base64 = { version = '0.20.0' }
env_logger = "0.10.0"
http = { version = "0.2.8" }
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    # 'tracing'
] }
tower-http = { version = '0.3.5', features = ['cors', 'trace'] }
tracing = '0.1.37'
tracing-subscriber = { version = '0.3.16', features = ['env-filter'] }
